name: Flutter Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
      
      # यह स्टेप चेक करेगा कि फाइल सही जगह है या नहीं
      - name: Check file existence
        run: |
          ls -R android/app/src/main/
      
      - run: flutter pub get
      - run: flutter build apk --release
